"""add chat_id column to message table

Revision ID: 933e77819c6e
Revises: 79d6f5ca1441
Create Date: 2025-09-07 15:33:35.487580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933e77819c6e'
down_revision: Union[str, None] = '79d6f5ca1441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###
